version: "3.9"

services:
  edsdoughcalc:
    image: python:3.11-slim
    container_name: edsdoughcalc
    restart: unless-stopped
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        apt-get update && apt-get install -y git && \
        git clone http://192.168.0.162:3002/edwardjgriggs/pizza-dough-calculator.git /app && \
        pip install --no-cache-dir -r /app/requirements.txt && \
        python /app/Dough_Calculator.py
    ports:
      - "5080:5000"
    volumes:
      - /DATA/AppData/edsdoughcalc:/app
    environment:
      - FLASK_ENV=production
      - TZ=America/New_York
