version: "3.9"

services:
  edsdoughcalc:
    image: python:3.11-slim
    container_name: edsdoughcalc
    restart: unless-stopped
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        apt-get update && apt-get install -y git && \
        git clone http://192.168.0.162:3002/edwardjgriggs/pizza-dough-calculator.git /app && \
        pip install --no-cache-dir -r /app/requirements.txt && \
        python /app/Dough_Calculator.py
    ports:
      - "5050:5000"                            # Access app via http://192.168.0.162:5050
    volumes:
      - /DATA/AppData/edsdoughcalc:/app        # CasaOS volume mount for persistence
    environment:
      - FLASK_ENV=production
      - TZ=America/New_York
    labels:
      io.casaos.category: "Utilities"
      io.casaos.title: "Pizza Dough Calculator"
      io.casaos.description: "Flask app to calculate pizza dough and ingredient weights."
      io.casaos.icon: "https://icon.casaos.io/main/all/python.png"
      io.casaos.port: "5050"
      io.casaos.web: "http://192.168.0.162:5050"
