version: "3.9"

services:
  doughcalc:
    image: python:3.11-slim
    container_name: doughcalc
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python Dough_Calculator.py"
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
