version: "3.9"

services:
  doughcalc:
    image: python:3.11-slim
    container_name: doughcalc
    restart: unless-stopped
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        pip install --no-cache-dir -r requirements.txt
        python Dough_Calculator.py
    ports:
      - "5050:5000"                            # Use 5050 externally so it doesn’t conflict
    volumes:
      - /DATA/AppData/doughcalc:/app           # Mount CasaOS app directory into /app
    environment:
      - FLASK_ENV=production
      - TZ=America/New_York
    labels:
      io.casaos.category: "Utilities"
      io.casaos.title: "Pizza Dough Calculator"
      io.casaos.description: "Flask app to calculate pizza dough and ingredient weights."
      io.casaos.icon: "https://icon.casaos.io/main/all/python.png"
      io.casaos.port: "5050"
      io.casaos.web: "http://192.168.0.162:5050"
